# Generated by Django 5.2.1 on 2025-05-27 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_title', models.CharField(max_length=255)),
                ('artist_name', models.CharField(max_length=255)),
                ('genre', models.CharField(choices=[('pop', 'Pop'), ('hip-hop', 'Hip Hop'), ('rnb', 'R&B'), ('rock', 'Rock'), ('afrobeat', 'Afrobeat'), ('reggae', 'Reggae'), ('electronic', 'Electronic'), ('indie', 'Indie'), ('gospel', 'Gospel'), ('worship', 'Worship'), ('christian-hiphop', 'Christian Hip Hop'), ('praise', 'Praise'), ('other', 'Other')], default='worship', max_length=100)),
                ('album_name', models.CharField(blank=True, max_length=100)),
                ('music_description', models.TextField()),
                ('tags', models.CharField(max_length=255)),
                ('music_file', models.FileField(default='music.mp3', upload_to='media/music')),
                ('up_loaded_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('quality', models.CharField(blank=True, max_length=50, null=True)),
                ('lyrics', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
