# Generated by Django 5.2.1 on 2025-05-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='featured',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
