# Generated by Django 5.2.1 on 2025-05-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_music_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='music_file',
            field=models.FileField(default='music.mp3', upload_to='music'),
        ),
    ]
